<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from assetlist/xml/schema/CRM/Assetlist/Asset.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:661cbd5b22188e72a2927e09d109dd14)
 */
use CRM_Assetlist_ExtensionUtil as E;

/**
 * Database access object for the Asset entity.
 */
class CRM_Assetlist_DAO_Asset extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_asset';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Asset ID
   *
   * @var int
   */
  public $id;

  /**
   * Asset Name
   *
   * @var string
   */
  public $name;

  /**
   * Virtual FK to Asset Type ID.
   *
   * @var int
   */
  public $asset_type_id;

  /**
   * A text-based description of the asset.
   *
   * @var string
   */
  public $asset_description;

  /**
   * FK to Contact that owns the asset (usually an organisation).
   *
   * @var int
   */
  public $asset_owner_contact_id;

  /**
   * FK to Contact that possesses the asset (usually an individual).
   *
   * @var int
   */
  public $asset_possessor_contact_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_asset';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Assets') : E::ts('Asset');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'asset_owner_contact_id', 'civicrm_contact', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'asset_possessor_contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Asset ID'),
          'required' => TRUE,
          'where' => 'civicrm_asset.id',
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'asset_name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Asset Name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_asset.name',
          'export' => TRUE,
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'add' => NULL,
        ],
        'asset_type_id' => [
          'name' => 'asset_type_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Asset Type ID'),
          'description' => E::ts('Virtual FK to Asset Type ID.'),
          'required' => TRUE,
          'where' => 'civicrm_asset.asset_type_id',
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'pseudoconstant' => [
            'optionGroupName' => 'asset_types',
            'optionEditPath' => 'civicrm/admin/options/asset_types',
          ],
          'add' => NULL,
        ],
        'asset_description' => [
          'name' => 'asset_description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Asset Description'),
          'description' => E::ts('A text-based description of the asset.'),
          'maxlength' => 850,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_asset.asset_description',
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'add' => NULL,
        ],
        'asset_owner_contact_id' => [
          'name' => 'asset_owner_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact that owns the asset (usually an organisation).'),
          'where' => 'civicrm_asset.asset_owner_contact_id',
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'asset_possessor_contact_id' => [
          'name' => 'asset_possessor_contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact that possesses the asset (usually an individual).'),
          'where' => 'civicrm_asset.asset_possessor_contact_id',
          'table_name' => 'civicrm_asset',
          'entity' => 'Asset',
          'bao' => 'CRM_Assetlist_DAO_Asset',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'asset', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'asset', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
